apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  labels:
    app: hello-world-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
        - name: hello-world-service
          image: gcr.io/hello-world-458306/hello-world-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: ClusterIP
  selector:
    app: hello-world-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
